services:
  api:
    container_name: drive-clone-api
    build: .
    ports:
      - "3000:3000"
    env_file:
      - .env
    environment:
      DATABASE_URL: postgresql://postgres:postgres@db:5432/drive-clone-db
    depends_on:
      - db

  db:
    container_name: drive-clone-db
    image: postgres:16-alpine
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: drive-clone-db
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata: